steps:
  - id: "Get latest image"
    name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args: ["-c", "docker pull ${_REPO}/${_IMAGE}:latest || exit 0"]

  - id: "Build image"
    waitFor: ["Get latest image"]
    name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "${_REPO}/${_IMAGE}:${_VERSION}",
        "--cache-from",
        "${_REPO}/${_IMAGE}:latest",
        "${_SRC}",
      ]

  - id: "Tag as latest"
    name: "gcr.io/cloud-builders/docker"
    args: ["tag", "${_REPO}/${_IMAGE}:${_VERSION}", "${_REPO}/${_IMAGE}:latest"]

  - id: "Push to AR"
    name: "gcr.io/cloud-builders/docker"
    waitFor: ["Build image", "Tag as latest"]
    args: ["push", "--all-tags", "${_REPO}/${_IMAGE}"]

  - id: "Set image in deployment"
    waitFor:
      - "Push to AR"
    # - "Apply k8s manifest"
    name: "gcr.io/cloud-builders/kubectl"
    args:
      [
        "set",
        "image",
        "deployment/${_RELEASE}",
        "${_CONTAINER}=${_REPO}/${_IMAGE}:${_VERSION}",
        "--namespace",
        "${_NAMESPACE}",
      ]
    env:
      - "CLOUDSDK_COMPUTE_REGION=${_REGION}"
      - "CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER}"

substitutions:
  _REPO: "us-west1-docker.pkg.dev/mslarkin-ext/mslarkin-docker"
  _SRC: "."
  _RELEASE: gke-mcp-server
  _CONTAINER: ${_RELEASE}
  _IMAGE: ${_RELEASE}
  _VERSION: $BUILD_ID
  _REGION: us-west1
  _CLUSTER: ai-auto-cluster
  _NAMESPACE: agent-ns

options:
  dynamicSubstitutions: true
  substitutionOption: "ALLOW_LOOSE"
  logging: CLOUD_LOGGING_ONLY
